-- TasteTable database
-- Run this file in Supabase SQL Editor.

create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  image_url text,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  total_amount numeric(10,2) not null check (total_amount >= 0),
  status text not null default 'Pending'
    check (status in ('Pending', 'Preparing', 'Out for delivery', 'Delivered', 'Cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  menu_item_id bigint not null references menu_items(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0)
);

-- Enable Row Level Security.
alter table menu_items enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

-- Public customers can read available menu items.
create policy "Anyone can view available menu items"
on menu_items for select
to anon
using (is_available = true);

-- Customers can create orders without signing in.
create policy "Anyone can create orders"
on orders for insert
to anon
with check (true);

create policy "Anyone can view orders"
on orders for select
to anon
using (true);

create policy "Anyone can create order items"
on order_items for insert
to anon
with check (true);

create policy "Anyone can view order items"
on order_items for select
to anon
using (true);

-- Optional sample menu data.
insert into menu_items (name, category, description, price, image_url)
select * from (values
  ('Creamy Alfredo Pasta', 'Pasta', 'Silky parmesan sauce, herbs and tender pasta.', 249.00, 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80'),
  ('Margherita Pizza', 'Pizza', 'Classic tomato, mozzarella and fresh basil.', 299.00, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80'),
  ('Crispy Chicken Burger', 'Burgers', 'Crunchy chicken, lettuce and house sauce.', 219.00, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80'),
  ('Paneer Tikka Bowl', 'Indian', 'Smoky paneer, rice, vegetables and mint chutney.', 229.00, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80'),
  ('Loaded French Fries', 'Sides', 'Golden fries with cheese, herbs and a creamy dip.', 149.00, 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80'),
  ('Chocolate Brownie', 'Desserts', 'Warm chocolate brownie with a soft fudgy centre.', 139.00, 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80')
) as sample(name, category, description, price, image_url)
where not exists (select 1 from menu_items);